Объекты и массивы, основы тестирования
js-tasks-ru/js-20210309-2_kdos pull request #3
Opened 2021-03-21 10:31 UTC by guood

2021-03-21 10:31 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-22 10:02 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let fieldValue;
если в переменную `fieldValue` присвоить сразу ссылку на `obj`, позволит ли это избавиться от тернарного условия ниже?

2021-03-22 10:02 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  if (!path) {
какую проблему решает данная конструкция?

2021-03-22 10:03 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
>  export function invertObj(obj) {
good 👍

2021-03-22 10:03 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2021-03-22 10:03 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
good 👍

2021-03-22 10:03 UTC, dosandk requested changes
необходимо дать ответы на вопросы

2021-03-22 14:28 UTC, guood commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let fieldValue;
Да, можно так, спасибо!
исправил

2021-03-22 14:30 UTC, guood commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  if (!path) {
Делаю проверку на случай, если по какой-то причине передадут в качестве пути null или undefine.
Логика была в том, что если такое передать, то пусть возвращается функция, возвращающая undefine. 
Семантически это должно быть правильно.
Но если вернем undefine, то тоже должно быть нормально.
Могу переделать так

2021-03-23 09:11 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  if (!path) {
оставляйте, но обращайте внимание на "пограничные кейсы" в тестах. Если в тестах есть описанный случай когда передается `undefined` или `null` тогда такую проверку следует сделать, во всех остальных случаях это не требуется

2021-03-23 09:11 UTC, dosandk approved these changes
good 👍

2021-03-23 09:11 UTC, merged

2021-03-23 09:12 UTC, guood commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  if (!path) {
Хорошо